# The Docker image that will be used to build your app
image: maven:3.9.0-eclipse-temurin-17-focal

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

pages:
  stage: deploy
  script:
    - mvn clean install jacoco:prepare-agent javadoc:javadoc -Dmaven.javadoc.failOnError=false
    - mvn site
    - mkdir -p public
    - cp -r target/site/jacoco public/
    - cp -r target/site/apidocs public/
    
  artifacts:
    paths:
      - public
    expire_in: never
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
